
  name: elements
  version: 1.2.1
  summary: The Modern Periodic Table.
  description: The modern periodic table using dart and flutter.
  confinement: strict
  base: core18
  architectures:
  - build-on: amd64
  apps:
    elements:
      command: Elements
      extensions: [flutter-master]
  parts:
    purple-task:
      source: .
      plugin: flutter
      flutter-target: lib/main.dart
